# svc-multi-match.yaml
apiVersion: v1
kind: Service
metadata:
  name: whoami-service-multi
spec:
  selector:
    app: whoami  # Matches both pods
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
