# whoami-pods.yaml
apiVersion: v1
kind: Pod
metadata:
  name: whoami-pod-1
  labels:
    app: whoami
spec:
  containers:
  - name: whoami
    image: sixeyed/whoami:21.04
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Pod
metadata:
  name: whoami-pod-2
  labels:
    app: whoami
spec:
  containers:
  - name: whoami
    image: sixeyed/whoami:21.04
    ports:
    - containerPort: 80
