apiVersion: apps/v1
kind: Deployment
metadata:
  name: whoami-v2-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: whoami
      version: v2
  template:
    metadata:
      labels:
        app: whoami
        version: v2
    spec:
      containers:
      - name: whoami
        image: containous/whoami
        ports:
        - containerPort: 80
