apiVersion: v1
kind: Pod
metadata:
  name: bad-sleep-pod
spec:
  containers:
  - name: bad-sleep
    image: courselabs/bad-sleep
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
